name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux x86_64 (musl for static linking)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            asset_name: axon-mcp-x86_64-unknown-linux-musl
            
          # Linux aarch64 (musl for static linking)
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            asset_name: axon-mcp-aarch64-unknown-linux-musl
            use_cross: true
            
          # macOS Universal Binary
          - os: macos-latest
            target: universal-apple-darwin
            asset_name: axon-mcp-universal-apple-darwin
            
          # Windows x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: axon-mcp-x86_64-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target != 'universal-apple-darwin' && matrix.target || '' }}

      - name: Install additional targets for macOS universal
        if: matrix.target == 'universal-apple-darwin'
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install cross
        if: matrix.use_cross
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      # Build for Linux/Windows single targets
      - name: Build binary
        if: matrix.target != 'universal-apple-darwin' && !matrix.use_cross
        run: |
          cargo build --release --target ${{ matrix.target }} --bin axon-mcp
          
      # Build using cross for aarch64-linux
      - name: Build binary with cross
        if: matrix.use_cross
        run: |
          cross build --release --target ${{ matrix.target }} --bin axon-mcp

      # Build macOS universal binary
      - name: Build macOS universal binary
        if: matrix.target == 'universal-apple-darwin'
        run: |
          # Build for both architectures
          cargo build --release --target x86_64-apple-darwin --bin axon-mcp
          cargo build --release --target aarch64-apple-darwin --bin axon-mcp
          
          # Create universal binary
          mkdir -p target/release
          lipo -create \
            target/x86_64-apple-darwin/release/axon-mcp \
            target/aarch64-apple-darwin/release/axon-mcp \
            -output target/release/axon-mcp

      # Prepare binary
      - name: Prepare binary
        shell: bash
        run: |
          # Rename binary to axon-mcp
          if [ "${{ matrix.target }}" = "universal-apple-darwin" ]; then
            # Already renamed in the lipo step
            BINARY_PATH="target/release/axon-mcp"
          elif [ "${{ runner.os }}" = "Windows" ]; then
            BINARY_PATH="target/${{ matrix.target }}/release/axon-mcp.exe"
            BINARY_PATH="target/${{ matrix.target }}/release/axon-mcp.exe"
          else
            BINARY_PATH="target/${{ matrix.target }}/release/axon-mcp"
            BINARY_PATH="target/${{ matrix.target }}/release/axon-mcp"
          fi
          
          # Strip binary (except on Windows)
          if [ "${{ runner.os }}" != "Windows" ]; then
            strip "$BINARY_PATH" || true
          fi
          
          echo "BINARY_PATH=$BINARY_PATH" >> $GITHUB_ENV

      # Install and run UPX for binary compression
      - name: Compress binary with UPX
        if: matrix.target != 'universal-apple-darwin' # UPX doesn't work well with universal binaries
        shell: bash
        run: |
          # Install UPX
          if [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y upx
          elif [ "${{ runner.os }}" = "Windows" ]; then
            choco install upx -y
          fi
          
          # Compress binary (best compression)
          if command -v upx >/dev/null 2>&1; then
            echo "Compressing binary with UPX..."
            upx --best --lzma "${{ env.BINARY_PATH }}" || true
            
            # Show size reduction
            ls -lh "${{ env.BINARY_PATH }}"
          fi

      # Package artifacts
      - name: Package artifacts
        shell: bash
        run: |
          mkdir -p dist
          
          if [ "${{ runner.os }}" = "Windows" ]; then
            # For Windows, create a zip file
            cd "$(dirname "${{ env.BINARY_PATH }}")"
            7z a "$GITHUB_WORKSPACE/dist/${{ matrix.asset_name }}.zip" "axon-mcp.exe"
            echo "ASSET_PATH=dist/${{ matrix.asset_name }}.zip" >> $GITHUB_ENV
          else
            # For Unix, create a tar.gz
            cd "$(dirname "${{ env.BINARY_PATH }}")"
            tar -czf "$GITHUB_WORKSPACE/dist/${{ matrix.asset_name }}.tar.gz" "axon-mcp"
            echo "ASSET_PATH=dist/${{ matrix.asset_name }}.tar.gz" >> $GITHUB_ENV
          fi

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ env.ASSET_PATH }}

  create-release:
    name: Create Release
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Generate checksums
        run: |
          cd dist
          # Find all tar.gz and zip files (artifacts are now in individual directories)
          find . -type f \( -name "*.tar.gz" -o -name "*.zip" \) -exec sha256sum {} \; > checksums.txt
          cat checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.tar.gz
            dist/**/*.zip
            dist/checksums.txt
            install.sh
            install.ps1
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update install script URL
        run: |
          echo "Installation script available at:"
          echo "https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh"
          echo ""
          echo "Quick install command:"
          echo "curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh | sh"